In [1]:
import pandas as pd
from plotnine import *

# importing statsmodels (for linear regression in python)
import statsmodels.formula.api as smf

/Users/shelbyjouppi/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [2]:
pd.set_option("display.max_columns",None)

## Load Data

#### Michigan air polluter documents & permit data
These are violation notices, activity reports (inspection), compliance evaluations etc...

In [3]:
doc_df = pd.read_csv("EGLE-AQD-documents-source-info.csv")

In [4]:
doc_df.head()

,name,doc_type,date,zip_code,county,full_address,source_id,geometry,doc_url
0,TUSCOLA ENERGY INC - RUMBLE SHARP CTB,ACO,2015-12-17,48767.0,TUSCOLA,"SE SW SW SEC 19 T14N R8E, AKRON, MI",N8277,"[-83.5141259, 43.5680758]",https://www.egle.state.mi.us/aps/downloads/srn...
1,TUSCOLA ENERGY INC-BOYCE JR TRUSTEE 1&STREETER 1,ACO,2015-12-17,48701.0,TUSCOLA,"SW SW SW SEC 24 T14N R7E, AKRON, MI",N8274,"[-83.4647598, 43.5678261]",https://www.egle.state.mi.us/aps/downloads/srn...
2,UNKNOWN,SAR,2019-07-16,49776.0,ALPENA,"ALPENA COUNTY, ALPENA, MI",U04060035,"[-83.4327528, 45.0616794]",https://www.egle.state.mi.us/aps/downloads/srn...
3,UNKNOWN,SAR,2020-05-07,49776.0,ALPENA,"ALPENA COUNTY, ALPENA, MI",U04060035,"[-83.4327528, 45.0616794]",https://www.egle.state.mi.us/aps/downloads/srn...
4,RIVERSIDE - FOREST HOME 12,FCE,2016-05-25,49611.0,ANTRIM,"SW 1/4 NE 1/4 SEC 12 T30N R8W, BELLAIRE, MI",N7824,"[-85.2111728, 44.9802822]",https://www.egle.state.mi.us/aps/downloads/srn...

In [5]:
pti_df = pd.read_csv("pti-list-clean.csv")

In [6]:
# List of sources that have permits to install
pti_srn = pti_df.srn.to_list()
pti_unique = []
for srn in pti_srn:
    if srn not in pti_unique:
        pti_unique.append(srn)

In [7]:
# Filter doc df to look at only facilities that have permits to pollute
doc_df = doc_df[doc_df.source_id.isin(pti_unique)]

In [8]:
doc_df[doc_df.county == 'KALAMAZOO'].sort_values(['name','date']).head(50)

,name,doc_type,date,zip_code,county,full_address,source_id,geometry,doc_url
10796,AGGREGATE INDUSTRIES - NB1 PORTABLE PLANT,VN,2014-04-29,49009.0,KALAMAZOO,"6000 WEST G AVENUE, KALAMAZOO, MI",N5998,"[-85.6678922, 42.3324905]",https://www.egle.state.mi.us/aps/downloads/srn...
10794,AGGREGATE INDUSTRIES - NB1 PORTABLE PLANT,RVN,2014-05-13,49009.0,KALAMAZOO,"6000 WEST G AVENUE, KALAMAZOO, MI",N5998,"[-85.6678922, 42.3324905]",https://www.egle.state.mi.us/aps/downloads/srn...
10797,AGGREGATE INDUSTRIES - NB1 PORTABLE PLANT,VN,2014-08-28,49009.0,KALAMAZOO,"6000 WEST G AVENUE, KALAMAZOO, MI",N5998,"[-85.6678922, 42.3324905]",https://www.egle.state.mi.us/aps/downloads/srn...
10795,AGGREGATE INDUSTRIES - NB1 PORTABLE PLANT,RVN,2014-09-15,49009.0,KALAMAZOO,"6000 WEST G AVENUE, KALAMAZOO, MI",N5998,"[-85.6678922, 42.3324905]",https://www.egle.state.mi.us/aps/downloads/srn...
10597,ALLNEX USA INC.,FCE,2016-09-08,49001.0,KALAMAZOO,"2715 MILLER RD, KALAMAZOO, MI",B1677,"[-85.5451255, 42.27125789999999]",https://www.egle.state.mi.us/aps/downloads/srn...
10599,ALLNEX USA INC.,SAR,2016-09-08,49001.0,KALAMAZOO,"2715 MILLER RD, KALAMAZOO, MI",B1677,"[-85.5451255, 42.27125789999999]",https://www.egle.state.mi.us/aps/downloads/srn...
10602,ALLNEX USA INC.,TEST,2017-05-16,49001.0,KALAMAZOO,"2715 MILLER RD, KALAMAZOO, MI",B1677,"[-85.5451255, 42.27125789999999]",https://www.egle.state.mi.us/aps/downloads/srn...
10603,ALLNEX USA INC.,TEST,2018-08-28,49001.0,KALAMAZOO,"2715 MILLER RD, KALAMAZOO, MI",B1677,"[-85.5451255, 42.27125789999999]",https://www.egle.state.mi.us/aps/downloads/srn...
10604,ALLNEX USA INC.,TEST,2018-08-29,49001.0,KALAMAZOO,"2715 MILLER RD, KALAMAZOO, MI",B1677,"[-85.5451255, 42.27125789999999]",https://www.egle.state.mi.us/aps/downloads/srn...
10600,ALLNEX USA INC.,SAR,2019-08-27,49001.0,KALAMAZOO,"2715 MILLER RD, KALAMAZOO, MI",B1677,"[-85.5451255, 42.27125789999999]",https://www.egle.state.mi.us/aps/downloads/srn...
10598,ALLNEX USA INC.,FCE,2021-06-08,49001.0,KALAMAZOO,"2715 MILLER RD, KALAMAZOO, MI",B1677,"[-85.5451255, 42.27125789999999]",https://www.egle.state.mi.us/aps/downloads/srn...
10601,ALLNEX USA INC.,SAR,2021-06-08,49001.0,KALAMAZOO,"2715 MILLER RD, KALAMAZOO, MI",B1677,"[-85.5451255, 42.27125789999999]",https://www.egle.state.mi.us/aps/downloads/srn...
11352,BELL'S BREWERY,SAR,2014-06-11,49053.0,KALAMAZOO,"8938 KRUM AVE, GALESBURG, MI",P0516,"[-85.4541575, 42.2841408]",https://www.egle.state.mi.us/aps/downloads/srn...
11353,BELL'S BREWERY,TEST,2015-04-22,49053.0,KALAMAZOO,"8938 KRUM AVE, GALESBURG, MI",P0516,"[-85.4541575, 42.2841408]",https://www.egle.state.mi.us/aps/downloads/srn...
11354,BELL'S BREWERY,VN,2015-11-05,49053.0,KALAMAZOO,"8938 KRUM AVE, GALESBURG, MI",P0516,"[-85.4541575, 42.2841408]",https://www.egle.state.mi.us/aps/downloads/srn...
11351,BELL'S BREWERY,RVN,2015-12-01,49053.0,KALAMAZOO,"8938 KRUM AVE, GALESBURG, MI",P0516,"[-85.4541575, 42.2841408]",https://www.egle.state.mi.us/aps/downloads/srn...
11356,BENTELER AUTOMOTIVE CORP,VN,2014-01-27,49053.0,KALAMAZOO,"9000 E MICHIGAN AVE, GALESBURG, MI",N2286,"[-85.4391693, 42.2870813]",https://www.egle.state.mi.us/aps/downloads/srn...
11355,BENTELER AUTOMOTIVE CORP,RVN,2014-02-10,49053.0,KALAMAZOO,"9000 E MICHIGAN AVE, GALESBURG, MI",N2286,"[-85.4391693, 42.2870813]",https://www.egle.state.mi.us/aps/downloads/srn...
10607,BORGESS MEDICAL CENTER,SAR,2020-09-15,49001.0,KALAMAZOO,"1521 GULL RD, KALAMAZOO, MI",E4168,"[-85.5605868, 42.3084515]",https://www.egle.state.mi.us/aps/downloads/srn...
10721,BRONSON MEHODIST HOSPITAL,SAR,2020-09-15,49007.0,KALAMAZOO,"601 JOHN ST, KALAMAZOO, MI",E4169,"[-85.5802999, 42.2856526]",https://www.egle.state.mi.us/aps/downloads/srn...
11701,CMS GENERATION KALAMAZOO RIVER GENERATING STATION,TEST,2014-01-24,49093.0,KALAMAZOO,"6900 EAST MICHIGAN AVENUE, COMSTOCK TWP, MI",N6731,"[-85.49317339999999, 42.2882953]",https://www.egle.state.mi.us/aps/downloads/srn...
11694,CMS GENERATION KALAMAZOO RIVER GENERATING STATION,FCE,2014-06-30,49093.0,KALAMAZOO,"6900 EAST MICHIGAN AVENUE, COMSTOCK TWP, MI",N6731,"[-85.49317339999999, 42.2882953]",https://www.egle.state.mi.us/aps/downloads/srn...
11697,CMS GENERATION KALAMAZOO RIVER GENERATING STATION,SAR,2014-06-30,49093.0,KALAMAZOO,"6900 EAST MICHIGAN AVENUE, COMSTOCK TWP, MI",N6731,"[-85.49317339999999, 42.2882953]",https://www.egle.state.mi.us/aps/downloads/srn...
11695,CMS GENERATION KALAMAZOO RIVER GENERATING STATION,FCE,2016-08-11,49093.0,KALAMAZOO,"6900 EAST MICHIGAN AVENUE, COMSTOCK TWP, MI",N6731,"[-85.49317339999999, 42.2882953]",https://www.egle.state.mi.us/aps/downloads/srn...
11698,CMS GENERATION KALAMAZOO RIVER GENERATING STATION,SAR,2016-08-11,49093.0,KALAMAZOO,"6900 EAST MICHIGAN AVENUE, COMSTOCK TWP, MI",N6731,"[-85.49317339999999, 42.2882953]",https://www.egle.state.mi.us/aps/downloads/srn...
11702,CMS GENERATION KALAMAZOO RIVER GENERATING STATION,TEST,2017-06-13,49093.0,KALAMAZOO,"6900 EAST MICHIGAN AVENUE, COMSTOCK TWP, MI",N6731,"[-85.49317339999999, 42.2882953]",https://www.egle.state.mi.us/aps/downloads/srn...
11696,CMS GENERATION KALAMAZOO RIVER GENERATING STATION,FCE,2018-01-24,49093.0,KALAMAZOO,"6900 EAST MICHIGAN AVENUE, COMSTOCK TWP, MI",N6731,"[-85.49317339999999, 42.2882953]",https://www.egle.state.mi.us/aps/downloads/srn...
11699,CMS GENERATION KALAMAZOO RIVER GENERATING STATION,SAR,2018-01-24,49093.0,KALAMAZOO,"6900 EAST MICHIGAN AVENUE, COMSTOCK TWP, MI",N6731,"[-85.49317339999999, 42.2882953]",https://www.egle.state.mi.us/aps/downloads/srn...
11703,CMS GENERATION KALAMAZOO RIVER GENERATING STATION,TEST,2018-11-01,49093.0,KALAMAZOO,"6900 EAST MICHIGAN AVENUE, COMSTOCK TWP, MI",N6731,"[-85.49317339999999, 42.2882953]",https://www.egle.state.mi.us/aps/downloads/srn...
11704,CMS GENERATION KALAMAZOO RIVER GENERATING STATION,TEST,2019-11-06,49093.0,KALAMAZOO,"6900 EAST MICHIGAN AVENUE, COMSTOCK TWP, MI",N6731,"[-85.49317339999999, 42.2882953]",https://www.egle.state.mi.us/aps/downloads/srn...
11700,CMS GENERATION KALAMAZOO RIVER GENERATING STATION,SAR,2020-03-06,49093.0,KALAMAZOO,"6900 EAST MICHIGAN AVENUE, COMSTOCK TWP, MI",N6731,"[-85.49317339999999, 42.2882953]",https://www.egle.state.mi.us/aps/downloads/srn...
11705,CMS GENERATION KALAMAZOO RIVER GENERATING STATION,TEST,2020-09-02,49093.0,KALAMAZOO,"6900 EAST MICHIGAN AVENUE, COMSTOCK TWP, MI",N6731,"[-85.49317339999999, 42.2882953]",https://www.egle.state.mi.us/aps/downloads/srn...
10612,CYTEC,TEST,2019-09-24,49001.0,KALAMAZOO,"3115 MILLER RD, KALAMAZOO, MI",P0447,"[-85.5458092, 42.2703236]",https://www.egle.state.mi.us/aps/downloads/srn...
10611,CYTEC,SAR,2019-10-04,49001.0,KALAMAZOO,"3115 MILLER RD, KALAMAZOO, MI",P0447,"[-85.5458092, 42.2703236]",https://www.egle.state.mi.us/aps/downloads/srn...
11550,"D & D AMALGAMATED SERVICES, INC.",VN,2021-05-06,49079.0,KALAMAZOO,"814 NOLA STREET, KALAMAZOO, MI",P1032,"[-85.59569499999999, 42.2986446]",https://www.egle.state.mi.us/aps/downloads/srn...
11551,"D & D AMALGAMATED SERVICES, INC.",VN,2021-06-17,49079.0,KALAMAZOO,"814 NOLA STREET, KALAMAZOO, MI",P1032,"[-85.59569499999999, 42.2986446]",https://www.egle.state.mi.us/aps/downloads/srn...
10614,DOMESTIC UNIFORM RENTAL,VN,2019-07-25,49001.0,KALAMAZOO,"3401 COVINGTON RD., KALAMAZOO, MI",N7298,"[-85.53820759999999, 42.2508466]",https://www.egle.state.mi.us/aps/downloads/srn...
10613,DOMESTIC UNIFORM RENTAL,RVN,2019-08-14,49001.0,KALAMAZOO,"3401 COVINGTON RD., KALAMAZOO, MI",N7298,"[-85.53820759999999, 42.2508466]",https://www.egle.state.mi.us/aps/downloads/srn...
11361,EATON CORPORATION - GALESBURG CAMPUS,TEST,2013-10-25,49053.0,KALAMAZOO,"13100 E MICHIGAN AVE, GALESBURG, MI",B2209,"[-85.3738497, 42.2766312]",https://www.egle.state.mi.us/aps/downloads/srn...
11362,EATON CORPORATION - GALESBURG CAMPUS,VN,2016-12-27,49053.0,KALAMAZOO,"13100 E MICHIGAN AVE, GALESBURG, MI",B2209,"[-85.3738497, 42.2766312]",https://www.egle.state.mi.us/aps/downloads/srn...
11357,EATON CORPORATION - GALESBURG CAMPUS,FCE,2017-01-11,49053.0,KALAMAZOO,"13100 E MICHIGAN AVE, GALESBURG, MI",B2209,"[-85.3738497, 42.2766312]",https://www.egle.state.mi.us/aps/downloads/srn...
11359,EATON CORPORATION - GALESBURG CAMPUS,RVN,2017-01-20,49053.0,KALAMAZOO,"13100 E MICHIGAN AVE, GALESBURG, MI",B2209,"[-85.3738497, 42.2766312]",https://www.egle.state.mi.us/aps/downloads/srn...
11358,EATON CORPORATION - GALESBURG CAMPUS,FCE,2021-06-07,49053.0,KALAMAZOO,"13100 E MICHIGAN AVE, GALESBURG, MI",B2209,"[-85.3738497, 42.2766312]",https://www.egle.state.mi.us/aps/downloads/srn...
11360,EATON CORPORATION - GALESBURG CAMPUS,SAR,2021-06-07,49053.0,KALAMAZOO,"13100 E MICHIGAN AVE, GALESBURG, MI",B2209,"[-85.3738497, 42.2766312]",https://www.egle.state.mi.us/aps/downloads/srn...
10620,EVERGREEN PACKAGING INC.,VN,2015-09-22,49001.0,KALAMAZOO,"2315 MILLER RD, KALAMAZOO, MI",B8574,"[-85.5494688, 42.2678902]",https://www.egle.state.mi.us/aps/downloads/srn...
10621,EVERGREEN PACKAGING INC.,VN,2015-12-04,49001.0,KALAMAZOO,"2315 MILLER RD, KALAMAZOO, MI",B8574,"[-85.5494688, 42.2678902]",https://www.egle.state.mi.us/aps/downloads/srn...
10617,EVERGREEN PACKAGING INC.,FCE,2015-12-09,49001.0,KALAMAZOO,"2315 MILLER RD, KALAMAZOO, MI",B8574,"[-85.5494688, 42.2678902]",https://www.egle.state.mi.us/aps/downloads/srn...
10616,EVERGREEN PACKAGING INC.,ACO,2016-04-01,49001.0,KALAMAZOO,"2315 MILLER RD, KALAMAZOO, MI",B8574,"[-85.5494688, 42.2678902]",https://www.egle.state.mi.us/aps/downloads/srn...
10622,EVERGREEN PACKAGING INC.,VN,2017-12-15,49001.0,KALAMAZOO,"2315 MILLER RD, KALAMAZOO, MI",B8574,"[-85.5494688, 42.2678902]",https://www.egle.state.mi.us/aps/downloads/srn...
10619,EVERGREEN PACKAGING INC.,RVN,2017-12-20,49001.0,KALAMAZOO,"2315 MILLER RD, KALAMAZOO, MI",B8574,"[-85.5494688, 42.2678902]",https://www.egle.state.mi.us/aps/downloads/srn...

In [9]:
doc_df.to_csv("mi-docs-active-pti.csv", index=False)

#### ACS Zip Code Poverty Level for Michigan

In [10]:
pov_df = pd.read_csv("ACS_MI_Zip_12MonthsPovertyLevelIncome_Pct.csv")

In [10]:
pov_df.head()

,Unnamed: 0,name,Total,"Total, Error",Income Poverty Level,"Income Poverty Level, Error"
0,0,Michigan,9741628,0.0,14.4,0.1
1,1,48001,11818,0.9,9.9,2.0
2,2,48002,3212,1.1,7.7,3.5
3,3,48003,6047,3.0,9.4,3.2
4,4,48005,5439,1.7,4.9,2.0

#### Michigan air polluters source list

In [11]:
source_df = pd.read_csv("EGLE-AQD-source-list.csv")

In [12]:
# Filter DF to look at only facilities that have permits to pollute
source_df = source_df[source_df.id.isin(pti_unique)]

In [13]:
source_df.head()

,id,name,zip_code,county,full_address,geometry
0,A6260,ALGONAC CAST PRODUCTS INC,48001.0,SAINT CLAIR,"9300 STONE ROAD, ALGONAC, MI","[-82.54572189999999, 42.6299997]"
2,N6769,SUNSATION PRODUCTS INC,48001.0,SAINT CLAIR,"9635 KRETZ DR, ALGONAC, MI","[-82.5700738, 42.6222489]"
3,P1024,ALTA EQUIPMENT COMPANY,48001.0,KENT,"8840 BYRON COMMERCE DRIVE, BYRON CENTER, MI","[-85.6703763, 42.80414830000001]"
5,P1089,CARL SCHEGEL,48001.0,JACKSON,"4500 MANN ROAD, CONCORD, MI","[-84.68608139999999, 42.1971472]"
6,P1015,"ENBRIDGE ENERGY, LP",48001.0,IRON,"SEC 35, T43N, R32W, CRYSTAL FALLS, MI","[-88.3340242, 46.0980066]"

In [17]:
sources_county = source_df[['id','county']].copy()

#### ACS Zip Code Race Demographics for Michigan

In [14]:
race_df = pd.read_csv("ACS_MI_Zip_RacePct.csv")

In [15]:
race_df.head()

,name,white_pct,black_pct,am_indian_ak_native_pct,asian_pct,hi_pc_islander_pct,other_pct
0,Michigan,78.4,13.8,0.5,3.1,0.0,4.1
1,48001,97.0,0.1,0.6,0.6,0.1,1.6
2,48002,98.7,0.0,0.0,0.0,0.0,1.3
3,48003,98.7,0.0,0.1,1.0,0.0,0.2
4,48005,97.0,0.8,0.4,0.2,0.0,1.7

## Clean data

#### Renaming columns

In [16]:
doc_df.columns = doc_df.columns.str.lower().str.replace(" ","_")

In [17]:
pov_df.columns = pov_df.columns.str.lower().str.replace(" ","_")

In [18]:
race_df.columns = race_df.columns.str.lower().str.replace(" ","_")

#### Change zip codes to str

In [19]:
doc_df.zip_code = doc_df.zip_code.astype("str").str[:5]

In [20]:
source_df.zip_code = source_df.zip_code.astype("str").str[:5]

#### Change to datetime

In [21]:
doc_df.date = pd.to_datetime(doc_df.date, format = "%Y-%m-%d")

## Creating New Data Frames

#### Sources -- Zip Code

In [22]:
zip_sources = source_df.groupby("zip_code").id.nunique().to_frame().rename({'id':'sources'},axis=1).reset_index()

In [23]:
zip_sources

    zip_code  sources
0      48001       17
1      48005        4
2      48006        2
3      48014        2
4      48015        1
..       ...      ...
617    49959        1
618    49960        1
619    49968        2
620    49969        2
621    49971        2

[622 rows x 2 columns]

#### Violations -- Zip Code & Source

In [26]:
vn = doc_df[doc_df.doc_type.str.contains('^vn',na=False,case=False)].sort_values(["source_id",'date'])

In [27]:
zip_vn = vn.zip_code.value_counts().to_frame().reset_index().rename({"zip_code":"violations","index":"zip_code"},axis=1)

In [28]:
zip_vn

    zip_code  violations
0      48211         124
1      48701          54
2      48706          51
3      48217          42
4      48168          37
..       ...         ...
360    48371           1
361    48423           1
362    49431           1
363    49286           1
364    48503           1

[365 rows x 2 columns]

In [31]:
source_vn = vn.source_id.value_counts().to_frame().reset_index().rename({'index':'source_id','source_id':'violations'},axis=1)

In [32]:
source_vn

    source_id  violations
0       M4148          92
1       B1493          41
2       N2688          36
3       A7809          31
4       M4545          27
..        ...         ...
827     N1908           1
828     N1912           1
829     N1935           1
830     N2070           1
831     P1219           1

[832 rows x 2 columns]

#### Compliance Evaluations -- Zip Code & Source

In [14]:
fce = doc_df[doc_df.doc_type.str.contains('fce',na=False,case=False)].sort_values(["source_id",'date'])

In [15]:
source_fce = fce.source_id.value_counts().to_frame().reset_index().rename({'index':'source_id','source_id':'fce'},axis=1)

In [16]:
source_df_fce = source_df.merge(source_fce,how='left',right_on='source_id',left_on='id')

In [17]:
source_df_fce.fce = source_df_fce.fce.fillna(0)

In [21]:
pti_df[['srn','city','approved','notes']].merge(source_df_fce,how='outer',left_on='srn',right_on='id').to_csv('sources_fce_permits.csv',index=False)

In [55]:
source_df_fce.query('fce ==0').county.value_counts().head(20)

WAYNE           198
OAKLAND         155
KENT            105
MACOMB          103
OTTAWA           55
BERRIEN          51
INGHAM           44
GENESEE          43
KALAMAZOO        41
MONROE           38
WASHTENAW        35
SAINT CLAIR      34
CALHOUN          34
MUSKEGON         33
SAINT JOSEPH     31
TUSCOLA          30
JACKSON          29
ALLEGAN          25
BAY              22
LENAWEE          22
Name: county, dtype: int64

In [57]:
source_df_fce.county.value_counts().head(20)

WAYNE           358
OAKLAND         233
KENT            194
MACOMB          159
OTTAWA           89
OTSEGO           73
BERRIEN          73
CALHOUN          61
SAINT CLAIR      61
GENESEE          60
MUSKEGON         59
KALAMAZOO        59
WASHTENAW        58
INGHAM           58
MONROE           51
SAINT JOSEPH     46
JACKSON          45
MONTMORENCY      43
ALLEGAN          41
BAY              38
Name: county, dtype: int64

In [53]:
source_df_fce.query('fce==0 and county=="KALAMAZOO"')

,id,name,zip_code,county,full_address,geometry,source_id,fce
7,P1029,HAVILAND PRODUCTS COMPANY,48001.0,KALAMAZOO,"2722 NORTH BURDICK STREET, KALAMAZOO, MI","[-85.5831575, 42.318596]",NaN,0.0
1410,E4168,BORGESS MEDICAL CENTER,49001.0,KALAMAZOO,"1521 GULL RD, KALAMAZOO, MI","[-85.5605868, 42.3084515]",NaN,0.0
1411,N7195,COMSTOCK POINT BP,49001.0,KALAMAZOO,"6300 E. MICHIGAN AVE., KALAMAZOO, MI","[-85.5059596, 42.2882347]",NaN,0.0
1412,P0447,CYTEC,49001.0,KALAMAZOO,"3115 MILLER RD, KALAMAZOO, MI","[-85.5458092, 42.2703236]",NaN,0.0
1413,N7298,DOMESTIC UNIFORM RENTAL,49001.0,KALAMAZOO,"3401 COVINGTON RD., KALAMAZOO, MI","[-85.53820759999999, 42.2508466]",NaN,0.0
1415,B1692,HECO,49001.0,KALAMAZOO,"3509 S. BURDICK STREET, KALAMAZOO, MI","[-85.57817390000001, 42.2561595]",NaN,0.0
1417,B0118,PARKER - AEROSPACE,49001.0,KALAMAZOO,"2220 PALMER AVE, KALAMAZOO, MI","[-85.5518815, 42.2693674]",NaN,0.0
1420,P0279,"SUNOCO, INCORPORATED (R&M)",49001.0,KALAMAZOO,"4117 PORTAGE ROAD, KALAMAZOO, MI","[-85.56012260000001, 42.2463149]",NaN,0.0
1421,E2842,"TOP GRADE AGGREGATES, LLC",49001.0,KALAMAZOO,"700 NAZARETH ROAD, KALAMAZOO, MI","[-85.5332835, 42.2993236]",NaN,0.0
1422,N7570,WESTWOOD LUMBER SALES INC,49001.0,KALAMAZOO,"910 SHELDON COURT, KALAMAZOO, MI","[-85.56874789999999, 42.2851411]",NaN,0.0
1423,B7149,ZOETIS LLC,49001.0,KALAMAZOO,"2605 EAST KILGORE RD, KALAMAZOO, MI","[-85.5478602, 42.2462995]",NaN,0.0
1424,P0425,LAKESHORE RECLAMATION & RESALE,49002.0,KALAMAZOO,"9702 PORTAGE ROAD, KALAMAZOO, MI","[-85.56804439999999, 42.1763588]",NaN,0.0
1425,N7127,HOSPITAL NETWORK INC,49002.0,KALAMAZOO,"4510 COMMERCIAL AVENUE, PORTAGE, MI","[-85.53507019999999, 42.2237275]",NaN,0.0
1426,N1396,KALAMAZOO STRIPPING & DERUSTING,49002.0,KALAMAZOO,"3921 E CENTRE STREET, PORTAGE, MI","[-85.5418275, 42.2019819]",NaN,0.0
1428,A2005,BORROUGHS CORPORATION,49004.0,KALAMAZOO,"3002 N. BURDICK ST., KALAMAZOO, MI","[-85.58275569999999, 42.3215757]",NaN,0.0
1429,B1679,AMERICAN PAPER MILLS OF MI LLC,49004.0,KALAMAZOO,"P.O. BOX 117, PARCHMENT, MI","[-85.5697296, 42.3280952]",NaN,0.0
1430,P0926,"BENIPAL GAS FOOD MART, LLC",49006.0,KALAMAZOO,"3320 RAVINE ROAD, KALAMAZOO, MI","[-85.6294751, 42.3145688]",NaN,0.0
1431,N7785,AT&T,49007.0,KALAMAZOO,"133 WEST LOVELL, KALAMAZOO, MI","[-85.5838809, 42.288279]",NaN,0.0
1432,E4169,BRONSON MEHODIST HOSPITAL,49007.0,KALAMAZOO,"601 JOHN ST, KALAMAZOO, MI","[-85.5802999, 42.2856526]",NaN,0.0
1434,B7546,HAMMOND ROTO-FINISH,49007.0,KALAMAZOO,"1600 DOUGLAS AVE, KALAMAZOO, MI","[-85.6021229, 42.3067796]",NaN,0.0
1435,B7990,HEXACOMB,49007.0,KALAMAZOO,"807 HARRISON, KALAMAZOO, MI","[-85.574778, 42.2998266]",NaN,0.0
1436,B1696,KALAMAZOO WATER RECLAMATION PLANT,49007.0,KALAMAZOO,"1415 N HARRISON ST., KALAMAZOO, MI","[-85.57431530000001, 42.3076562]",NaN,0.0
1441,N6980,WMU ENERGY RESOURCE CENTER,49008.0,KALAMAZOO,"4701 CAMPUS DRIVE, KALAMAZOO, MI","[-85.6444794, 42.256135]",NaN,0.0
1442,N5998,AGGREGATE INDUSTRIES - NB1 PORTABLE PLANT,49009.0,KALAMAZOO,"6000 WEST G AVENUE, KALAMAZOO, MI","[-85.6678922, 42.3324905]",NaN,0.0
1443,P1135,C2 EXCAVATING,49009.0,KALAMAZOO,"10 D AVE W, KALAMAZOO, MI","[-85.59066, 42.3770774]",NaN,0.0
1444,N1317,"GENERAL ELECTRIC CO., CARBOLOY SYSTEMS DEPT",49009.0,KALAMAZOO,"7694 WEST MICHIGAN AVENUE, KALAMAZOO, MI","[-85.66266, 42.2672899]",NaN,0.0
1445,P0946,LANGELAND CREMATION CENTER,49009.0,KALAMAZOO,"3926 SOUTH 9TH STREET, KALAMAZOO, MI","[-85.67840029999999, 42.2527448]",NaN,0.0
1446,N8298,NEXT DOOR OPERATIONS LLC,49009.0,KALAMAZOO,"5658 W MAIN ST, KALAMAZOO, MI","[-85.6597226, 42.2964522]",NaN,0.0
1535,P1007,BALKEMA EXCAVATING INC. - PLANT 107,49048.0,KALAMAZOO,"1500 RIVER STREET, KALAMAZOO, MI","[-85.5202051, 42.27488140000001]",NaN,0.0
1536,N7390,BALKEMA EXCAVATING INC.-PLANT 104,49048.0,KALAMAZOO,"1500 RIVER STREET, KALAMAZOO, MI","[-85.5202051, 42.27488140000001]",NaN,0.0
1538,P1130,KALAMAZOO HUMANE SOCIETY,49048.0,KALAMAZOO,"2272 RIVER STREET, KALAMAZOO, MI","[-85.52192579999999, 42.2677566]",NaN,0.0
1539,P0669,"LANDSCAPE FORMS, INC.",49048.0,KALAMAZOO,"5262 E CORK STREET, KALAMAZOO, MI","[-85.5224058, 42.2581298]",NaN,0.0
1541,P0516,BELL'S BREWERY,49053.0,KALAMAZOO,"8938 KRUM AVE, GALESBURG, MI","[-85.4541575, 42.2841408]",NaN,0.0
1542,N2286,BENTELER AUTOMOTIVE CORP,49053.0,KALAMAZOO,"9000 E MICHIGAN AVE, GALESBURG, MI","[-85.4391693, 42.2870813]",NaN,0.0
1578,P1032,"D & D AMALGAMATED SERVICES, INC.",49079.0,KALAMAZOO,"814 NOLA STREET, KALAMAZOO, MI","[-85.59569499999999, 42.2986446]",NaN,0.0
1604,N7211,KAL-MARBLE & GRANITE INC.,49087.0,KALAMAZOO,"2820 HAGAR DR., SCHOOLCRAFT, MI","[-85.6226887, 42.1121867]",NaN,0.0
1639,N6415,"EIMO TECHNOLOGIES, INC.",49097.0,KALAMAZOO,"14300 PORTAGE RD, VICKSBURG, MI","[-85.5702206, 42.1103354]",NaN,0.0
1641,P0728,VAN ELDEREN INC.,49097.0,KALAMAZOO,"130 S. LEJA DRIVE, VICKSBURG, MI","[-85.5471795, 42.1207453]",NaN,0.0
2712,P0466,KIWI & COMPANY,49009.0,KALAMAZOO,"7019 WEST Q AVENUE, KALAMAZOO, MI","[-85.687085, 42.200925]",NaN,0.0
2717,N2170,"WKW EXTRUSION, ERBSLOEH ALUMINUM SOLUTIONS, INC.",49002.0,KALAMAZOO,"6565 SPRINKLE RD, PORTAGE, MI","[-85.5370814, 42.2220361]",NaN,0.0
2719,N6246,PRECISION HEAT TREATING CO,49007.0,KALAMAZOO,"660 GULL STREET, KALAMAZOO, MI","[-85.572828, 42.2978808]",NaN,0.0

In [38]:
zip_fce = fce.zip_code.value_counts().to_frame().reset_index().rename({"zip_code":"fce","index":"zip_code"},axis=1)

#### SAR -- Zip Code & Source

In [39]:
sar = doc_df[doc_df.doc_type.str.contains('sar',na=False,case=False)].sort_values(["source_id",'date'])

In [40]:
source_sar = sar.source_id.value_counts().to_frame().reset_index().rename({'index':'source_id','source_id':'sar'},axis=1)

In [70]:
zip_sar = sar.zip_code.value_counts().to_frame().reset_index().rename({"zip_code":"sar","index":"zip_code"},axis=1)

In [42]:
source_sar

     source_id  sar
0        A4043   57
1        A4033   25
2        N2688   23
3        A9831   14
4        B1477   14
...        ...  ...
2009     N6097    1
2010     N6102    1
2011     N6103    1
2012     N6122    1
2013     P1219    1

[2014 rows x 2 columns]

### Merging Data by Source & Demographic Information

In [48]:
df = source_df.merge(source_fce,how="outer",right_on="source_id", left_on="id")
df = df.merge(source_sar,how="outer",right_on="source_id", left_on="id")
df = df.merge(source_vn, how="outer",right_on="source_id", left_on="id")

In [49]:
df.head()

,id,name,zip_code,county,full_address,geometry,source_id_x,fce,source_id_y,sar,source_id,violations
0,A6260,ALGONAC CAST PRODUCTS INC,48001,SAINT CLAIR,"9300 STONE ROAD, ALGONAC, MI","[-82.54572189999999, 42.6299997]",NaN,NaN,A6260,1.0,NaN,NaN
1,N6769,SUNSATION PRODUCTS INC,48001,SAINT CLAIR,"9635 KRETZ DR, ALGONAC, MI","[-82.5700738, 42.6222489]",NaN,NaN,N6769,2.0,NaN,NaN
2,P1024,ALTA EQUIPMENT COMPANY,48001,KENT,"8840 BYRON COMMERCE DRIVE, BYRON CENTER, MI","[-85.6703763, 42.80414830000001]",NaN,NaN,NaN,NaN,NaN,NaN
3,P1089,CARL SCHEGEL,48001,JACKSON,"4500 MANN ROAD, CONCORD, MI","[-84.68608139999999, 42.1971472]",NaN,NaN,NaN,NaN,NaN,NaN
4,P1015,"ENBRIDGE ENERGY, LP",48001,IRON,"SEC 35, T43N, R32W, CRYSTAL FALLS, MI","[-88.3340242, 46.0980066]",NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df = df.drop(['source_id_x','source_id_y','source_id'],axis=1)

In [52]:
df.fce = df.fce.fillna(0)
df.sar = df.sar.fillna(0)
df.violations = df.violations.fillna(0)

In [53]:
df

,id,name,zip_code,county,full_address,geometry,fce,sar,violations
0,A6260,ALGONAC CAST PRODUCTS INC,48001,SAINT CLAIR,"9300 STONE ROAD, ALGONAC, MI","[-82.54572189999999, 42.6299997]",0.0,1.0,0.0
1,N6769,SUNSATION PRODUCTS INC,48001,SAINT CLAIR,"9635 KRETZ DR, ALGONAC, MI","[-82.5700738, 42.6222489]",0.0,2.0,0.0
2,P1024,ALTA EQUIPMENT COMPANY,48001,KENT,"8840 BYRON COMMERCE DRIVE, BYRON CENTER, MI","[-85.6703763, 42.80414830000001]",0.0,0.0,0.0
3,P1089,CARL SCHEGEL,48001,JACKSON,"4500 MANN ROAD, CONCORD, MI","[-84.68608139999999, 42.1971472]",0.0,0.0,0.0
4,P1015,"ENBRIDGE ENERGY, LP",48001,IRON,"SEC 35, T43N, R32W, CRYSTAL FALLS, MI","[-88.3340242, 46.0980066]",0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
2786,N0200,LAMBDA ENERGY RESOURCES LLC - OTSEGO LAKE 34,49797,OTSEGO,"913 SOFTWOOD TR., WATERS, MI","[-84.6485314, 44.8682625]",2.0,2.0,1.0
2787,P1069,ALTA EQUIPMENT COMPANY,49779,PRESQUE ISLE,"1035 CALCITE ROAD, ROGERS CITY, MI","[-83.8075728, 45.41887500000001]",0.0,0.0,0.0
2788,P0067,LAURIE HAMMAR,49880,DELTA,"15524 NORTH ROCK 38TH RD, ROCK, MI","[-87.14493639999999, 46.10608380000001]",0.0,1.0,0.0
2789,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0
2790,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,0.0

In [57]:
# Merge poverty data
df = df.merge(pov_df,how='left',left_on='zip_code',right_on="name") \
.drop(["total,_error","income_poverty_level,_error","unnamed:_0","name_y"],axis=1)

In [60]:
# Merge race data
df = df.merge(race_df,how='left',left_on='zip_code',right_on="name").drop(['name'],axis=1)

In [63]:
df.to_csv("fce-sar-violations-by-source.csv",index=False)

### Getting permit start date and duration

In [95]:
pti_df.head()

,company,srn,address,city,zip_code,pti_no.,approved,notes
0,"RIVERSIDE ENERGY MICHIGAN, LLC",N8170,SECTION 32 - MOUNT MARIA CPF,ALCONA TOWNSHIP,48721.0,329-08,12/17/2008,NaN
1,"LAMBDA ENERGY RESOURCES, LLC",N7470,"SW SW NW SEC 10, T28N - CALEDONIA",CALEDONIA TOWNSHIP,49735.0,109-05,7/6/2005,NaN
2,TRENDWELL ENERGY CORPORATION,N7901,"NW NE SEC 20, T8N, R6E - WOLF CREEK",CALEDONIA TOWNSHIP,48762.0,349-07,1/9/2008,NaN
3,RIVERSIDE ENERGY MICHIGAN,N8070,"NW NE SEC 20, T8N, R6E",CALEDONIA TOWNSHIP,48619.0,188-08,6/30/2008,NaN
4,"LAMBDA ENERGY RESOURCES, LLC",N8074,"SW 1/4 SE 1/4 NE 1/4 SEC 8, T28N, R8E -",CALEDONIA TOWNSHIP,49316.0,199-08A,1/14/2011,NaN

In [101]:
from datetime import date
today = date.today()
today = pd.to_datetime(today)
import numpy as np

In [96]:
# Converting permit approval date to datetime
pti_df.approved = pd.to_datetime(pti_df.approved, format="%m/%d/%Y")

In [97]:
# Multiple permits per source so let's take the earliest permit date for each source
pti_approved_date = pti_df.groupby("srn").approved.min().to_frame().reset_index()

In [102]:
# Converting to years
pti_approved_date['years'] = today - pti_approved_date.approved
pti_approved_date.years = pti_approved_date.years/np.timedelta64(1, 'Y')

In [103]:
# I only have 9 years worth of data so if a permit is longer than 9 years 
# we are going to just say 9 to keep the rate consistent with the data
def years_convert(years):
    if years > 9:
        return 9.0
    else: 
        return years

In [104]:
pti_approved_date['years_converted'] = pti_approved_date.years.apply(years_convert)

In [105]:
pti_approved_date

        srn   approved      years  years_converted
0     A0023 2001-04-12  20.969630         9.000000
1     A0083 2015-01-14   7.211647         7.211647
2     A0085 2016-04-27   5.927569         5.927569
3     A0098 2004-11-29  17.336427         9.000000
4     A0099 2000-08-08  21.645893         9.000000
...     ...        ...        ...              ...
2991  P1249 2021-12-14   0.295694         0.295694
2992  P1251 2022-02-01   0.161537         0.161537
2993  P1252 2022-02-01   0.161537         0.161537
2994  P1253 2022-02-08   0.142371         0.142371
2995  P1257 2022-03-15   0.046544         0.046544

[2996 rows x 4 columns]

In [108]:
df = df.merge(pti_approved_date,how="left",right_on="srn", left_on="id")

In [110]:
df['fce_per_year'] = df.fce / df.years_converted

In [111]:
df.head()

,id,name_x,zip_code,county,full_address,geometry,fce,sar,violations,total,income_poverty_level,white_pct,black_pct,am_indian_ak_native_pct,asian_pct,hi_pc_islander_pct,other_pct,srn,approved,years,years_converted,fce_per_year
0,A6260,ALGONAC CAST PRODUCTS INC,48001,SAINT CLAIR,"9300 STONE ROAD, ALGONAC, MI","[-82.54572189999999, 42.6299997]",0.0,1.0,0.0,11818.0,9.9,97.0,0.1,0.6,0.6,0.1,1.6,A6260,2014-01-23,8.186342,8.186342,0.0
1,N6769,SUNSATION PRODUCTS INC,48001,SAINT CLAIR,"9635 KRETZ DR, ALGONAC, MI","[-82.5700738, 42.6222489]",0.0,2.0,0.0,11818.0,9.9,97.0,0.1,0.6,0.6,0.1,1.6,N6769,2014-09-18,7.534720,7.534720,0.0
2,P1024,ALTA EQUIPMENT COMPANY,48001,KENT,"8840 BYRON COMMERCE DRIVE, BYRON CENTER, MI","[-85.6703763, 42.80414830000001]",0.0,0.0,0.0,11818.0,9.9,97.0,0.1,0.6,0.6,0.1,1.6,P1024,2019-05-13,2.885754,2.885754,0.0
3,P1089,CARL SCHEGEL,48001,JACKSON,"4500 MANN ROAD, CONCORD, MI","[-84.68608139999999, 42.1971472]",0.0,0.0,0.0,11818.0,9.9,97.0,0.1,0.6,0.6,0.1,1.6,P1089,2019-10-29,2.423048,2.423048,0.0
4,P1015,"ENBRIDGE ENERGY, LP",48001,IRON,"SEC 35, T43N, R32W, CRYSTAL FALLS, MI","[-88.3340242, 46.0980066]",0.0,0.0,0.0,11818.0,9.9,97.0,0.1,0.6,0.6,0.1,1.6,P1015,2021-05-25,0.851489,0.851489,0.0

In [112]:
df.to_csv("documents-by-source-demographics.csv",index=False)

#### Merge all zip code level data

In [81]:
zip_df = source_df.zip_code.value_counts().to_frame().reset_index().rename({'index':'zip_code','zip_code':'sources'},axis=1)

In [83]:
# Merge FCE
zip_df = zip_df.merge(zip_fce,how="outer",left_on="zip_code",right_on="zip_code")

In [85]:
# Merge SAR
zip_df = zip_df.merge(zip_sar,how="outer",left_on="zip_code",right_on="zip_code")

In [86]:
# Merge Violations
zip_df = zip_df.merge(zip_vn,how="outer",left_on="zip_code",right_on="zip_code")

In [87]:
# Merge poverty data
zip_df = zip_df.merge(pov_df,how='left',left_on='zip_code',right_on="name")

In [88]:
# Merge race data
zip_df = zip_df.merge(race_df, how="left",left_on="zip_code",right_on="name")

In [92]:
zip_df = zip_df.drop(['unnamed:_0','name_x','total,_error','name_y','income_poverty_level,_error'],axis=1)

In [93]:
zip_df.to_csv("violations-fce-sar-by-zip.csv",index=False)